name: Morning Data Ingestion

on:
  schedule:
    - cron: "40 1 * * 1-5" # 8:40 AM GMT+7 (Monday-Friday)
  workflow_dispatch:

jobs:
  ingest_morning:
    runs-on: ubuntu-latest
    timeout-minutes: 200 # Runs until 12:00 PM GMT+7 (200 mins from 8:40 AM)

    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Ingestion
        env:
          REDIS_URL: redis://localhost:6379
        run: |
          # Run for 195 minutes (11700 seconds), then automatically terminate
          timeout 195m python src/ingestion/producer.py &
          timeout 195m python src/ingestion/consumer.py &

          # Wait for the timeout to finish the processes.
          # The || true catches the timeout exit code so the step turns Green!
          wait || true

      - name: Upload output files
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: morning-ingestion-data
          path: ./data/pubsub/
