name: Do things every minute

on:
  schedule:
    - cron: "* * * * *"
  workflow_dispatch:

jobs:
  test_cron:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print message
        run: echo "This job runs every minute!"
